### PR TITLE
add hapi-info

### PR DESCRIPTION
**Pull request by danielb2**
hapi-info adds route to show hapi version and plugin version

Added to utility section

### CODE REVIEW

**Comment by hueniverse** [comment]
So basically, you re-implemented furball :-)

**Comment by danielb2** [comment]
I was worried for a moment I'd missed a plugin for a moment :)

**Comment by danielb2** [comment]
If it makes more sense, we can revive furball instead?

**Comment by hueniverse** [comment]
I don't care.

**Comment by nlf** [comment]
i'm gonna go ahead and merge this, but yeah maybe it would be best to revive furball and then take this down later..

**Pull request merged**
