### PR TITLE
add security page #64

### PR DESCRIPTION
**Pull request by rdela**
add security page #64
- lib/routes.js
- templates/security.jade

appease eslint no-trailing-spaces
- lib/plugins.js

### CODE REVIEW

**Comment by AdriVanHoudt** [comment]
nice 👍  maybe it also needs some info on how security issues are handled?

**Comment by rdela** [comment]
Thanks @AdriVanHoudt saw this http://blog.npmjs.org/post/167524001790/couchdb-vulnerabilities-and-the-npm-registry and thought the last paragraph had some good language along the lines you mention

**Comment by rdela** [comment]
```
We deeply appreciate the responsible disclosure and cooperative spirit displayed by Max Justicz, who also made sure we were patched in advance of making his blog post. If you are aware of a package vulnerability or a vulnerability in any of npm’s system, please do contact us via email: security@npmjs.com.
```

Speaking of @nlf are we go for security@hapijs.com
?
https://hapihour.slack.com/archives/C6ATVCFC0/p1510788828000169

**Comment by rdela** [comment]
Also https://www.npmjs.com/policies/security

**Comment by rdela** [comment]
May also be worth pointing to handling of past issues:
https://github.com/hapijs/hapi/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Asecurity%20

Nothing new and par for the course I suppose, but I was particularly impressed with the maturity and quickness:
https://github.com/hapijs/hapi/issues/3466 /
https://nodesecurity.io/advisories/hapi_denial-of-service-via-malformed-accept-encoding-header
was dealt with.

**Comment by hueniverse** [comment]
Why close?

**Pull request closed without merging**
