### PR TITLE
Add release notes to relevant milestones

### LINKED ISSUE #231: Link release notes
It seems for some people (espacially newcomers) it is hard to find the release note. The new updates helps but does not include the actual release note.
Would it be possible to link the issue with the matching milestone and `release notes` label to the milestones on the /updates page?

### PR DESCRIPTION
**Pull request by Marsup**
Fixes #231.

Not sure if it's the best way to do that, anyway since everything's already cached, I didn't want to modify those, so render time it is.

### CODE REVIEW

**Comment by AdriVanHoudt** [comment]
Can you show a screenshot of the result?

**Comment by Marsup** [comment]
notes

**Comment by AdriVanHoudt** [comment]
LGTM

**Comment by nlf** [comment]
:+1: nice, thanks!

**Pull request merged**
