### PR TITLE
Updated all dependencies

### PR DESCRIPTION
**Pull request by AdriVanHoudt**
For some reason using the `building-static-server` errors on my machine with 
```js
$ npm start

> hapijs.com@1.0.0 start c:\Users\adri\Documents\GitHub\HapiJS\hapijs.com
> node server.js

  bss:info Livereload ready +0ms
  bss:info Build queued +3ms
  bss:info Build started +302ms
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn npm ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickDomainCallback (node.js:381:11)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! hapijs.com@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hapijs.com@1.0.0 start script 'node server.js'.
npm ERR! This is most likely a problem with the hapijs.com package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls hapijs.com
npm ERR! There is likely additional logging output above.
```

Without it it works fine.

### CODE REVIEW

**Comment by nlf** [comment]
nice, this is a good start. i have a few other changes that i want to make along with this, so i'm going to hold off on merging until i have time to take care of that stuff as well

**Comment by AdriVanHoudt** [comment]
Ok, if I can help with anyting let me know

**Comment by AdriVanHoudt** [comment]
any update on this?

**Comment by AdriVanHoudt** [comment]
anything I can do to either push this or the other stuff you were talking about?

**Comment by nlf** [comment]
yes, sorry.

so let's start off making sure these are still all the latest versions, then let's just remove building-static-server completely for now until we come up with something better.

**Comment by AdriVanHoudt** [comment]
hmm I don't get the error anymore (might be windows related, on mac now) will rebase first and go from there

**Comment by AdriVanHoudt** [comment]
ok so I am failing with my rebase :D will do a new PR

**Pull request closed without merging**
