### PR TITLE
Improve API sidebar nav

### PR DESCRIPTION
**Pull request by mtharrison**
Tries to address some of the issues here: https://github.com/hapijs/hapijs.com/issues/200
- Use bootstrap affix plugin to affix the API sidenav
- Use bootstrap scrollspy to show position in doc
- Autoscroll menu

This adds a very trimmed down version of Bootstrap with no CSS and only the Affix and Scrollspy jQuery plugins. There's a bit of custom code to get the menu to autoscroll to current position - this isn't something scrollspy does by itself.

scrollspy

This isn't perfect but I think it's a lot better than what we have now. Welcome feedback/improvements.

### CODE REVIEW

**Comment by devinivy** [comment]
This is good news!

**Comment by nlf** [comment]
we used to have the nav follow the scroll position, but we removed it and i can't seem to find the issue that explained why right now.. i personally like the idea, but i wish i could remember why we took it out.

do we really need to bring in both jquery and bootstrap just for this?

also you've got quite a few lines in the diff that are removing whitespace that should be there. we don't have linting of the client side code right now, but i do try to adhere to the hapi style guide anyway

**Comment by mtharrison** [comment]
> we used to have the nav follow the scroll position, but we removed it and i can't seem to find the issue that explained why right now.. i personally like the idea, but i wish i could remember why we took it out.

Do you mean the menu was just fixed position or the actual scroll position of the menu tracked the scroll position of the body too? I can only find commits that set it to fixed and change the menu height (e72b81e and reverted in f68104e).

> do we really need to bring in both jquery and bootstrap just for this?

It's bringing in a tiny bit of bootstrap (6k) with only the 2 plugins. But yes they're jQuery plugins so it requires jQuery (86k). If you're worried about that though, I could look into if there's an alternative lib or if it's something we can write ourselves easily enough. 

> also you've got quite a few lines in the diff that are removing whitespace that should be there. we don't have linting of the client side code right now, but i do try to adhere to the hapi style guide anyway

I'll fix this. Think my editor changed it by itself.

**Comment by mtharrison** [comment]
Added help wanted because I'm unlikely to find any time to improve this soon.

**Pull request closed without merging**
