### PR TITLE
Added hapi-mongoose to the plugins list

### PR DESCRIPTION
**Pull request by adriana-saroz**
A plugin that maps mongoose models to hapi routes

### CODE REVIEW

**Comment by Marsup** [comment]
The name is a bit misleading since it's actually `@watchup/hapi-mongoose`.

**Comment by adriana-saroz** [comment]
@Marsup thanks, I've updated the name

**Comment by franvarney** [comment]
@Marsup, none of the others are like that so doesn't it make sense for @adriana-saroz to do `hapi-mongoose` instead of `@watchup/hapi-mongoose`?

**Comment by Marsup** [comment]
hapi-mongoose already exists and it's not this one. I think it's better to give the npm name on the site so there are no conflicts or mistakes.

**Comment by mtharrison** [comment]
There's not another one on the list. And this one looks dead: https://www.npmjs.com/package/hapi-mongoose. The repo has been deleted and module not touched for a year.

**Comment by Marsup** [comment]
Yes but people will instinctively do `npm install <copy/paste>` and that's simply not its npm name.

**Comment by mtharrison** [comment]
Yeah, my bad. I deleted my comment when I realised.

**Comment by nlf** [comment]
yeah i agree with @marsup on this one, sticking to npm module names is the way to go.

thanks for the contribution @adriana-saroz!

**Comment by adriana-saroz** [comment]
Thanks! :seedling:

**Pull request merged**
