### PR TITLE
Tighten up plugins page whitespace. Closes #285

### LINKED ISSUE #285: Tighten up plugins page whitespace
The plugins page is getting pretty scroll-tastic. Wonder if reducing some of the whitespace between plugins would make it a bit of a better experience?

screen shot 2015-10-30 at 22 44 03

### PR DESCRIPTION
**Pull request by mtharrison**
Before/After:

Before/After

### CODE REVIEW

**Comment by mtharrison** [comment]
Closes #285

**Comment by AdriVanHoudt** [comment]
LGTM

**Comment by nlf** [comment]
i agree, this is nicer. thanks!

**Comment by mtharrison** [comment]
No problem :)

**Pull request merged**
