### PR TITLE
Add hapijs-status-monitor to Logging/Metrics section

### PR DESCRIPTION
**Pull request by ziyasal**
plugin [link](https://github.com/ziyasal/hapijs-status-monitor)

### CODE REVIEW

**Comment by Marsup** [comment]
FWIW several comments :
- you should not add methods to JavaScript native types
- you should not directly depend on hapi, it's a plugin, it should be a peer dependency
- your .npmignore could probably also ignore misc and .vscode
- you should use an actual server.route instead of hijacking the onPreResponse
- your response time measurement is wrong, you're measuring the time between 2 statements, explaining the impossible response times of ~0.0010ms

**Comment by ziyasal** [comment]
hi @Marsup thank you for your review 👍 I will refactor it asap (:

**Comment by Marsup** [comment]
Cool plugin btw, I only mentioned what I found wrong but it's a great addition !

**Comment by ziyasal** [comment]
hi @Marsup, thanks! btw, I have made quick refactoring to cover review and pushed new version.

**Pull request merged**
