### PR TITLE
add hapi-view-models plugin

### PR DESCRIPTION
**Pull request by antony**
Adds the hapi-view-models plugin we created for filtering payload data based on scopes.

### CODE REVIEW

**Comment by AdriVanHoudt** [comment]
@antony I think this belongs in the Templating category no?

**Comment by antony** [comment]
@AdriVanHoudt I was torn, I couldn't find the ideal category - realistically it has nothing to with templating, it's about restricting returned data based on credentials. I felt like it was closer to a security plugin than a rendering plugin, as it doesn't really provide any rendering support.

I don't know - I'm happy to move it if you feel it belongs somewhere else.

**Comment by AdriVanHoudt** [comment]
@antony I must have misread then :P, in that case Authorization sounds logical to me

**Comment by antony** [comment]
Not sure how I missed that - done!

**Pull request merged**
