### PR TITLE
plugins update: hapi-marko

### PR DESCRIPTION
**Pull request by pvde**

### CODE REVIEW

**Comment by Marsup** [comment]
I'd question referencing such plugins that are bad citizens, there's a well established view architecture in place (vision) it should integrate into that, makes for a much simpler life for end users.

**Comment by nlf** [comment]
that's a valid concern.. is there a reason this module doesn't just integrate with vision?

**Comment by pvde** [comment]
Ok thank you for the feedback. I will close this pull request for now since i'm not the maintainer of this plugin. @Marsup: Is there a page somewhere with guidelines on how plugins should be developed?

**Comment by Marsup** [comment]
No but this one was kind of obvious considering how all of the other plugins did it.

**Pull request closed without merging**
