### PR TITLE
Add Akaya utility plugins

### PR DESCRIPTION
**Pull request by felixheck**

### CODE REVIEW

**Comment by mtharrison** [comment]
It's a common practice (requirement?) to add your name to the license as an addition, rather than removing original author:

http://programmers.stackexchange.com/questions/114701/what-are-the-legal-considerations-when-forking-a-bsd-licensed-project

**Comment by mtharrison** [comment]
I think you need to update URL here:

> or clone the repository:
> 
> // development version with ES6 syntax
> $ git clone https://github.com/mtharrison/akaya

**Comment by Marsup** [comment]
Why add babel when all you're using are node 4 features ?

**Comment by Marsup** [comment]
Can't merge that btw, need to rebase on master.

**Pull request closed without merging**
