### PR TITLE
add a book

### PR DESCRIPTION
**Pull request by jjude**
Added a book 'Hapi with Typescript', a book that teaches to develop Hapi applications using Typescript

### CODE REVIEW

**Comment by AdriVanHoudt** [comment]
Cool, 1 thing though, hapi is always written lowercased ;)

**Comment by jjude** [comment]
Modified all instances to lowercase. Anything else needed?

**Comment by Marsup** [comment]
Yes, valid and correctly indented code, the tests won't pass until then.

**Comment by mtharrison** [comment]
Minor nit: Javascript should be JavaScript

**Pull request merged**
