### PR TITLE
style fix

### PR DESCRIPTION
**Pull request by danielb2**
* [callbacks should be made with explicit returns](https://github.com/hapijs/contrib/blob/master/Style.md#callback)

### CODE REVIEW

**Comment by Marsup** [comment]
I'm not sure I would consider reply a callback.

**Comment by danielb2** [comment]
What is it then? Also, the doc is inconsistent with some of them using an explicit return statement.

**Comment by danielb2** [comment]
I suppose you're right. it's not actually a callback now that I think of it

**Comment by Marsup** [comment]
It's an API call. You can still do stuff afterwards, like tails.

**Pull request closed without merging**
