### PR TITLE
Translated the tutorials to Turkish

### PR DESCRIPTION
**Pull request by erdemkeren**

### CODE REVIEW

**Comment by erdemkeren** [comment]
Thanks!

**Comment by erdemkeren** [comment]
Do anyone care about this request?

**Comment by devinivy** [comment]
I do!  @nlf is this the type of thing that we can merge as long as it's working?  It would be great to get one other Turkish speaker (especially with hapi familiarity) to do a quick overview of this work if possible.  I would read through it for clarity/correctness if only I spoke Turkish!  Thanks for your contribution @erdemkeren—this is great.

**Comment by nlf** [comment]
yeah, we can merge these at any time. i'm going to go ahead and merge this and we can always ask for revisions later if someone brings up an issue with the translation :) thanks @erdemkeren!

**Pull request merged**
