### PR TITLE
Fix footer container

### PR DESCRIPTION
**Pull request by thefoxis**
screen shot 2015-09-16 at 13 47 06

Currently footer is erroneously shifted to the left. Fixed it to be centered and unified the spacing between the footer and main content.

### CODE REVIEW

**Comment by AdriVanHoudt** [comment]
Can you still croll in the menu of hapijs.com/api? I believe @nlf did this as a fix for that

**Comment by thefoxis** [comment]
@AdriVanHoudt — uhm, true. will try to amend this along with the sidebar style fix then. feels off on the non-reference pages.

**Comment by nathanbuchar** [comment]
Ah, was about to start fixing the footer alignment as well! :+1:

**Comment by nlf** [comment]
closing this one in favor of #271 

lots more style fixes coming from the wonderful @thefoxis in the future though :D

**Comment by AdriVanHoudt** [comment]
:raised_hands:

**Pull request closed without merging**
