### PR TITLE
Remove old gh issue link, add PR info

### PR DESCRIPTION
**Pull request by antony**

### CODE REVIEW

**Comment by Marsup** [comment]
@nlf do you want more user guidance on this one ? Like a small text mentioning where to put the logo, explaining the width, ...

**Comment by antony** [comment]
@Marsup This is a good point - I'll add the info from the original Issue this afternoon.

**Comment by nlf** [comment]
hmm, that's a good point @marsup. a little more guidance might be beneficial. maybe we should put a blurb in the readme about how to add yourself to the community page and change the link to point to that? that way we keep the section in the community page short, but we still have the details somewhere useful

thoughts?

**Comment by antony** [comment]
Happy to make this change to the PR if @Marsup is also in agreement :)

**Comment by AdriVanHoudt** [comment]
ping @Marsup

**Comment by Marsup** [comment]
Didn't think you needed my agreement. @nlf's instructions seem to make sense.

**Comment by antony** [comment]
Alright I'll jump on this when I get a second :)

**Comment by antony** [comment]
Btw I'm not sure I understand the 'width' parameter myself. Going to figure out and add some extra detail.

**Comment by antony** [comment]
@nlf let me know if this works for you :)

**Pull request closed without merging**
