### PR TITLE
Update plugins.js

### PR DESCRIPTION
**Pull request by toymachiner62**
Added hapi-authorization

### CODE REVIEW

**Comment by mtharrison** [comment]
Just out of curiosity, what does this offer over the built-in scopes functionality?

**Comment by toymachiner62** [comment]
Idk. I'm not familiar with the scopes functionality. Can you point me to some good documentation?

**Comment by mtharrison** [comment]
You can find `scope` under [route options](http://hapijs.com/api#route-options).

There's also this blog post: https://blog.andyet.com/2015/06/16/harnessing-hapi-scopes/ and an SO answer I wrote a while back http://stackoverflow.com/a/29053887/1402929.

**Comment by toymachiner62** [comment]
Without diving too deeply into scopes, one thing that it provides is hierarchical authorizations. 

Do scopes allow you to blacklist all routes so that they require a certain role without having to specify on every route? Like this: https://www.npmjs.com/package/hapi-authorization#blacklist-all-routes-to-require-authorization

**Comment by nlf** [comment]
You can set a default required scope for every route, which effectively does the same thing.

**Comment by toymachiner62** [comment]
Interesting. Well maybe hapi-authorization is obsolete then. 

@AdrieanKhisbe @asafdav do you guys know of any other differences between hapi-authorization/hapi-auth-extra that the built in hapi scope does not provide?

**Comment by asafdav** [comment]
Hi @toymachiner62 I think that the main difference is ACL support

**Pull request merged**
