### PR TITLE
Packt URL added

### PR DESCRIPTION
**Pull request by tanS30**
Packt reference added.

### CODE REVIEW

**Comment by hueniverse** [comment]
This is the wrong place for this link. It should go with the rest of the books.

**Comment by tanS30** [comment]
Can you please let us know where to add the URL, we cannot find the rest of the books section.
Apologies for posting at the wrong place.

**Comment by mtharrison** [comment]
The book is already on the resource page: https://github.com/hapijs/hapijs.com/blob/master/lib/resources.js#L14-L17

**Comment by hueniverse** [comment]
Then that's pretty much it.

**Pull request closed without merging**
