### PR TITLE
pt-br tutorials

### PR DESCRIPTION
**Pull request by alanleite**
translation tutorials pt-br

### CODE REVIEW

**Comment by AdriVanHoudt** [comment]
:clap: awesome, just of curiosity if the tutorials get updated will you guys/girls also keep the translation up to date?

**Comment by alanleite** [comment]
Hi, thank you. It is our intention!

**Comment by devinivy** [comment]
Wow!  This is great– many thanks.

**Comment by nlf** [comment]
many thanks indeed! i'll get to work making these accessible as soon as i can

**Comment by thebergamo** [comment]
:shipit:

**Comment by nlf** [comment]
sorry for the delay on this, i'm currently lacking time to get these integrated into the site. i'm hoping to work on that soon.

**Comment by thebergamo** [comment]
If you wanna any help, I'm here to help =D

**Comment by thebergamo** [comment]
Any news about this PR? Maybe I can help to ship it :)

**Comment by Marsup** [comment]
I believe the lack of any internationalization layer is the problem here. (and lack of time indeed)

**Comment by thebergamo** [comment]
Well, I will try create a way to enable internationalization for the Hapi's
site :)

**Comment by nlf** [comment]
yeah.. i just haven't had any time to add internationalization support to the site. if you can find a clean way to implement it i'd be happy to merge it :)

**Comment by thebergamo** [comment]
off course :) just give me a couple of days

**Comment by thebergamo** [comment]
This branch can be closed. Are merged in the #408

**Comment by nlf** [comment]
superseded by #408

**Pull request closed without merging**
