### PR TITLE
Add hapi-next under Utility

### PR DESCRIPTION
**Pull request by Pranay92**
This module allows user to add modularity to the route handlers by allowing long function to be divided into small independent functions and be called in any sequence. This is also integrated with Travis-CI and has tests to ensure stable releases.

### CODE REVIEW

**Comment by hueniverse** [comment]
How is this different in functionality from prerequisites?

**Comment by Pranay92** [comment]
I'm sorry I didn't understood your statement. Is that achievable by default in hapi without using any plugins? I was trying to ind something like that but couldn't get it and ended up implementing the plugin itself. Please let me know if that's what you meant?

**Comment by hueniverse** [comment]
Take a look at the prerequisite feature in hapi and see if it does what you want.

**Comment by nlf** [comment]
@Pranay92 have you had a chance to look at prerequisites? if you have and you feel like this plugin is still useful it would be cool if you could add a note to your readme saying what's different about it.

**Comment by Pranay92** [comment]
Hi @nlf apologies for the delayed response. I've been using hapi-next in our project in quite a while now, and for me its more of an opinion to add everything at one place(eg. in your handler) and then control the flow(the way its done in hapi-next) while also having modularity. I've added a few more options in the latest release of hapi-next (like passing on error status when any of the series function fails), please have a look at the updated readme too.

Also, after reading the read me, if you aren't satisfied enough feel free to reject this PR or (preferably) accept this :)

Thank you for the patience.

**Comment by nlf** [comment]
updated readme looks nice and good usage info, thanks!

**Pull request merged**
