### PR TITLE
Add link to App Engine tutorial. Add Google Inc. to list of copyright owners.

### PR DESCRIPTION
**Pull request by jmdobry**
We love Hapi.js and wrote a simple getting started tutorial for deploying your Hapi.js app to Google App Engine. This PR adds a link to that tutorial in Hapi's list of links to examples/tutorials.

Our [sample app](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/master/appengine/hapi) is on GitHub, and we'd love any feedback/contributions.

### CODE REVIEW

**Comment by nlf** [comment]
this is great, thank you!

**Comment by nlf** [comment]
just curious how you felt about removing the specific google copyright, since this contribution is only a link to an external resource i'm not sure it warrants adding a specific mention to google in the license. also the current 2015 copyright lists "and other contributors" which should encompass any outside contributions regardless.

what are your thoughts?

**Comment by jmdobry** [comment]
Thanks for the merge!

> what are your thoughts?

I would tend to agree, and it's not something that I personally would have been concerned about adding for something so simple, but it's what I had to do to get my patch approved internally. Perhaps there is some other needed contribution to make the addition more warranted.

Technically, every contributor (entity) that retains copyright of their contribution (no CLA here) could/should have their name listed at the top of the license. The names of individuals would then be in a contributors file.

e.g. `Yahoo Inc.` listed as a copyright owner in the license, then the names of multiple Yahoo employees in the contributors file.

**Comment by AdriVanHoudt** [comment]
what if you add https://github.com/hapijs/hapijs.com/graphs/contributors to the license to link to 'other contributors' ofcourse this does not work for companies

**Comment by hueniverse** [comment]
This is not what we do. We add copyright for actual copyright, not adding a link.

**Comment by AdriVanHoudt** [comment]
Not following. Also just saw the link is already in there

**Pull request merged**
