### PR TITLE
fixes issue #215 Can't click on some footer links

### PR DESCRIPTION
**Pull request by joshvoll**
fixing the footer links
modified file: /css/sections/footer.styl

### CODE REVIEW

**Comment by Marsup** [comment]
Way too many changes on modes. Also this is not the correct solution for having tested this myself, this needs a much deeper reorganization of the elements. While this method fixes it apparently, the sidebar is still overflowing on the bottom if you unfold it enough, which happens very easily in the API section.

**Comment by joshvoll** [comment]
thanks for the comment, let me make other improvements

**Comment by nlf** [comment]
wow, yeah. i'll need you to revert all the file mode change commits for sure. also don't commit the `config/default.json` file, instead create a `config/local.json` file with your real key in it. you're gonna want to regenerate that key asap since it's now public.

also, i agree with @marsup this is a step in the right direction, but it's not quite there yet. good effort so far though!

**Comment by joshvoll** [comment]
Thanks @nlf let me revert all the file change, and keep working on this issue

**Comment by joshvoll** [comment]
@nlf i just reverted the file to the lasted commit, please review and let me know

**Comment by joshvoll** [comment]
Also i just generated a new token for myself, going to work fixing the click issue now

**Pull request closed without merging**
