### PR TITLE
updated all the dependencies

### PR DESCRIPTION
**Pull request by AdriVanHoudt**

### CODE REVIEW

**Comment by AdriVanHoudt** [comment]
continuation of https://github.com/hapijs/hapijs.com/pull/176

**Comment by AdriVanHoudt** [comment]
@nlf do you want me to just remove `building-static-server`? I would just recommend nodemon or something but that doesn't re-make thought

**Comment by nlf** [comment]
if it's working now, let's leave it. i think we'll eventually replace it with webpack or something though

**Comment by AdriVanHoudt** [comment]
idd, probably was a windows issue, also what is the reason for the special build for hapi? looks like v3 is even with your hapi8 branch?

**Comment by nlf** [comment]
it hadn't been published at the time, go ahead and change it to the regular release

**Comment by AdriVanHoudt** [comment]
:+1:

**Pull request merged**
