### PR TITLE
add four plugins of me: hapi-plugin-traffic, hapi-plugin-websocket, hapi-plugin-header, hapi-plugin-ducky

### PR DESCRIPTION
**Pull request by rse**
This adds four new HAPI plugins which I recently developed.

### CODE REVIEW

**Comment by Marsup** [comment]
Just curious, why make hapi-plugin-websocket when it seems already covered by nes ? Am I missing something ?

**Comment by rse** [comment]
I wanted a more seamless integration, i.e., I wanted that (a) everything was through POST-based routes only (no server.subscribe() or something), (b) responses like HTTP 204 (no content) are treated in a reasonable manner (no result messages) and (c) that I can control whether a route is both REST and WebSocket or just WebSocket-only. So, NES is just fine in general if you need WebSocket support in a HAPI environment. But if you want the mentioned features then HAPI-plugin-WebSocket can be a lightweight alternative.

**Comment by devinivy** [comment]
I don't see anything wrong with a little choice/competition among modules!  hapi-io also exists in a similar space too– they're all different.  This one seems fairly minimal, which is pretty cool if it works well.

**Comment by devinivy** [comment]
@rse did you intend to close this issue?

**Comment by rse** [comment]
Sorry, no, my fault. I just wanted to comment and by accident hit "close and comment".

**Comment by rse** [comment]
The README of hapi-plugin-websocket now has some hints to NES and the distinction between the two.

**Comment by Marsup** [comment]
I didn't mean that it shouldn't exist, I just wanted to grasp the difference, no problem having competition, even better.

**Pull request merged**
