### PR TITLE
Update the "Getting Started" tutorials for v17

### PR DESCRIPTION
**Pull request by sparkertime**
!!! THIS IS NOT READY TO MERGE YET EVEN IF YOU ARE BLOWN AWAY BY MY WORK !!!

Hello Hapi friends! I've been working through the tutorials with Hapi v17 and updating the examples as I go. I thought I'd see if these updates are useful to y'all before I start on any others.

Technically, this doesn't totally work until `good` promotes the `8.0` branch past RC. Once that happens, the instructions below should be correct. However, I didn't want to wait on that for feedback.

Feel free to say it's too soon to update the tutorials, no hurt feelings if this work is thrown away. Thanks!

### CODE REVIEW

**Comment by devinivy** [comment]
Thank you so much!  Overall this looks great.  I will leave some comments when I find a moment, but for starters you can inspect the CI checks.  We lint the tutorials to ensure the code sticks to the hapi style guide, and it seems there are a small handful of errors coming from that.  In your local setup you should be able to reproduce by running `npm test`.

**Comment by devinivy** [comment]
It is worth noting that there's a similar effort in https://github.com/hapijs/hapijs.com/pull/521

**Comment by sparkertime** [comment]
Ah, great, then I have no qualms if mine is tossed aside.

Thanks for the pointer on linting - will definitely keep that in mind if my
PR endures for some reason.

**Comment by JustinBeaudry** [comment]
@sparkertime Is this PR still relevant? Seems like Tutorials for hapi v17 have been added.

**Pull request closed without merging**
