### PR TITLE
Added multines to plugins

### PR DESCRIPTION
**Pull request by mcollina**

### CODE REVIEW

**Comment by devinivy** [comment]
Excited to try this plugin out some time

**Comment by mcollina** [comment]
Let me know what you think of it! PR always welcomed.

**Comment by nlf** [comment]
very neat! i agree with @devinivy i can't wait to play with this

**Comment by mcollina** [comment]
It should work even with cluster and child-process if used with https://github.com/mcollina/mqemitter-child-process. I need to write some more docs :D.

**Pull request merged**
