### PR TITLE
Add hapi-hubspot to plugins listings

### PR DESCRIPTION
**Pull request by asilluron**
Add listing for hapi plugin that handles [Hubspot](https://www.hubspot.com/) handshake and initial setup via [Node-Hubspot](https://github.com/brainflake/node-hubspot)

### CODE REVIEW

**Comment by Marsup** [comment]
@asilluron Are you sure you wanted to push your github ssh keys ? oO

**Comment by asilluron** [comment]
OMG, good catch. haha

**Comment by asilluron** [comment]
@Marsup thank you again for actually checking the repo.

Fixed.

**Comment by Marsup** [comment]
If I were you I'd regenerate keys and delete the old ones from anywhere you've used them, they are still in the git history.

**Pull request merged**
